export type GameRole = 'minigame' | 'sponsor' | 'employee' | 'competitor' | 'hazard' | 'powerup' | 'event' | 'milestone' | 'caddy' | 'course' | 'clubhouse' | 'trophy' | 'equipment';

export interface GameEntity {
  id: string;
  originalRepo: string;
  name: string;
  description: string;
  role: GameRole;
  icon: string;
  rarity: 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';
}

export const GAME_ENTITIES: GameEntity[] = [
  { id: '1-android-calculator', originalRepo: '1_Android_Calculator-master', name: '1 Android Calculator Solutions', description: 'UI library showcase', role: 'course', icon: '💻', rarity: 'common' },
  { id: '2-android-todolist', originalRepo: '2_Android_ToDoList-master', name: '2 Android Todolist LLC', description: 'AI advice that is probably wrong', role: 'caddy', icon: '🎉', rarity: 'common' },
  { id: '2048', originalRepo: '2048-main', name: 'Exponential Exit Strategy', description: 'Another game we built instead of working', role: 'minigame', icon: '🐳', rarity: 'uncommon' },
  { id: '3-android-geocamera', originalRepo: '3_Android_GeoCamera-master', name: '3 Android Geocamera Corp', description: 'Academic achievement unlocked', role: 'milestone', icon: '🎵', rarity: 'common' },
  { id: '4-android-restclient', originalRepo: '4_Android_RestClient-master', name: '4 Android Restclient Co', description: 'Middleware that middleware middlewares', role: 'employee', icon: '📦', rarity: 'common' },
  { id: '4th-district-event-scraper', originalRepo: '4th-district-event-scraper-master', name: '4th District Event Scraper Co', description: 'Frontend framework of the month club', role: 'course', icon: '🎲', rarity: 'uncommon' },
  { id: 'acme-cafe', originalRepo: 'ACME-Cafe-main', name: 'MVP Kitchen', description: 'AI advice that is probably wrong', role: 'caddy', icon: '🌐', rarity: 'uncommon' },
  { id: 'acme', originalRepo: 'acme-master', name: 'Acme Corp', description: 'Learning documented for posterity', role: 'trophy', icon: '🔒', rarity: 'uncommon' },
  { id: 'acrelab-cdl', originalRepo: 'acrelab-cdl-main', name: 'Acrelab Cdl Inc', description: 'AI advice that is probably wrong', role: 'caddy', icon: '🎨', rarity: 'uncommon' },
  { id: 'acreops-gcsproxy-fork', originalRepo: 'acreops-gcsproxy-fork-master', name: 'Acreops Gcsproxy Fork Factory', description: 'Built our product as a side project', role: 'competitor', icon: '🐱', rarity: 'uncommon' },
  { id: 'actual-budget-local', originalRepo: 'actual-budget-local-master', name: 'Actual Budget Local Factory', description: 'Boosts velocity by 2x maybe', role: 'powerup', icon: '🐛', rarity: 'uncommon' },
  { id: 'adopt-a-pet', originalRepo: 'Adopt_A_Pet-main', name: 'Adopt A Pet Ventures', description: 'The model works on my machine', role: 'caddy', icon: '🏠', rarity: 'uncommon' },
  { id: 'ads-test', originalRepo: 'ads-test-main', name: 'Ads Test Ventures', description: 'Boosts velocity by 2x maybe', role: 'powerup', icon: '💻', rarity: 'common' },
  { id: 'advent-of-code', originalRepo: 'advent-of-code-main', name: 'December Debug Club', description: 'From zero to one star on GitHub', role: 'milestone', icon: '⚖️', rarity: 'uncommon' },
  { id: 'ag-water-delta', originalRepo: 'ag_water_delta-master', name: 'Ag Water Delta Academy', description: 'Achievement unlocked and forgotten', role: 'trophy', icon: '👥', rarity: 'uncommon' },
  { id: 'alacritty', originalRepo: 'alacritty-master', name: 'Terminal Velocity', description: 'Where hot takes meet cold PRs', role: 'event', icon: '👥', rarity: 'legendary' },
  { id: 'android-crossfithelper', originalRepo: 'Android_CrossfitHelper-master', name: 'Android Crossfithelper Collective', description: 'The tool you did not know you needed', role: 'powerup', icon: '🌱', rarity: 'common' },
  { id: 'android-datalabeler', originalRepo: 'Android_DataLabeler-master', name: 'Android Datalabeler Industries', description: 'One domain to rule them all', role: 'sponsor', icon: '🎲', rarity: 'common' },
  { id: 'angular-website', originalRepo: 'Angular-Website-master', name: 'Angular Website Ventures', description: 'Resume but make it interactive', role: 'sponsor', icon: '📦', rarity: 'uncommon' },
  { id: 'aoc', originalRepo: 'AoC-main', name: 'Aoc Industries', description: 'ML predictions with confidence intervals of maybe', role: 'caddy', icon: '🎓', rarity: 'uncommon' },
  { id: 'apcsa-highlights', originalRepo: 'APCSA-Highlights-main', name: 'Apcsa Highlights Academy', description: 'The model works on my machine', role: 'caddy', icon: '🎯', rarity: 'uncommon' },
  { id: 'api-docs', originalRepo: 'api_docs-master', name: 'Api Docs LLC', description: 'Backend so powerful nobody uses it', role: 'employee', icon: '📦', rarity: 'uncommon' },
  { id: 'arkansas-trail-weather', originalRepo: 'arkansas-trail-weather-main', name: 'Arkansas Trail Weather Collective', description: 'AI advice that is probably wrong', role: 'caddy', icon: '🎮', rarity: 'uncommon' },
  { id: 'ar-maps', originalRepo: 'ar-maps-main', name: 'Ar Maps Inc', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '📝', rarity: 'uncommon' },
  { id: 'art369', originalRepo: 'art369-main', name: 'Art369 Industries', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '🎳', rarity: 'uncommon' },
  { id: 'ascii-magic', originalRepo: 'ascii-magic-master', name: 'Ascii Magic Inc', description: 'AI advice that is probably wrong', role: 'caddy', icon: '🔓', rarity: 'uncommon' },
  { id: 'asp-shop', originalRepo: 'ASP_Shop-master', name: 'Asp Shop Solutions', description: 'The repo that got a star', role: 'trophy', icon: '📱', rarity: 'uncommon' },
  { id: 'audiovisual-v2', originalRepo: 'audiovisual_v2-master', name: 'Audiovisual V2 Ventures', description: 'The tool you did not know you needed', role: 'powerup', icon: '🔄', rarity: 'uncommon' },
  { id: 'audiovisual-v3', originalRepo: 'audiovisual_v3-master', name: 'Audiovisual V3 Inc', description: 'Engagement is our growth metric', role: 'event', icon: '🐦', rarity: 'uncommon' },
  { id: 'audiovisual', originalRepo: 'audiovisual-master', name: 'Audiovisual Academy', description: 'Backend so powerful nobody uses it', role: 'employee', icon: '💵', rarity: 'uncommon' },
  { id: 'austinspinazze', originalRepo: 'AustinSpinazze-main', name: 'Austinspinazze Factory', description: 'The model works on my machine', role: 'caddy', icon: '⚛️', rarity: 'uncommon' },
  { id: 'auto-requirements', originalRepo: 'auto-requirements-master', name: 'Auto Requirements Industries', description: 'They ship while we debate tabs vs spaces', role: 'competitor', icon: '📊', rarity: 'uncommon' },
  { id: 'awesome-compose', originalRepo: 'awesome-compose-master', name: 'Docker Dream Weavers', description: 'Infrastructure anxiety as a feature', role: 'hazard', icon: '🗺️', rarity: 'legendary' },
  { id: 'babyyoda-project', originalRepo: 'BabyYoda_Project-main', name: 'Babyyoda Project Studios', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '📊', rarity: 'uncommon' },
  { id: 'barebonesreact', originalRepo: 'BareBonesReact-master', name: 'Barebonesreact Corp', description: 'Components all the way down', role: 'course', icon: '📝', rarity: 'common' },
  { id: 'barter-game', originalRepo: 'barter-game-master', name: 'Trade Simulator 3000', description: 'Another game we built instead of working', role: 'minigame', icon: '🏠', rarity: 'uncommon' },
  { id: 'bb-parking', originalRepo: 'bb_parking-main', name: 'Bb Parking Co', description: 'ML predictions with confidence intervals of maybe', role: 'caddy', icon: '📰', rarity: 'uncommon' },
  { id: 'best-quotes', originalRepo: 'best_quotes-master', name: 'Best Quotes LLC', description: 'App complete enough to demo', role: 'clubhouse', icon: '⚡', rarity: 'uncommon' },
  { id: 'book-app', originalRepo: 'Book-App-main', name: 'Book App Inc', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '🎓', rarity: 'common' },
  { id: 'boomerang-delay-plugin-vst-au', originalRepo: 'Boomerang-Delay-Plugin-VST-AU--master', name: 'Boomerang Delay Plugin Vst Au Systems', description: 'Learning projects as trophies', role: 'milestone', icon: '🐍', rarity: 'uncommon' },
  { id: 'bootcamp-examples', originalRepo: 'bootcamp-examples-master', name: 'Bootcamp Examples Systems', description: 'From zero to one star on GitHub', role: 'milestone', icon: '🔗', rarity: 'common' },
  { id: 'bradleyswilson-github-io', originalRepo: 'bradleyswilson.github.io-main', name: 'Bradleyswilson Github Io Co', description: 'Resume but make it interactive', role: 'sponsor', icon: '🔒', rarity: 'uncommon' },
  { id: 'braze-ruby', originalRepo: 'braze_ruby-main', name: 'Braze Ruby Inc', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '🚀', rarity: 'uncommon' },
  { id: 'braze-docs', originalRepo: 'braze-docs-develop', name: 'Braze Docs Co', description: 'YAML nightmares and config drift', role: 'hazard', icon: '🎯', rarity: 'uncommon' },
  { id: 'breaker', originalRepo: 'breaker-main', name: 'Breaker LLC', description: 'The model works on my machine', role: 'caddy', icon: '🏠', rarity: 'uncommon' },
  { id: 'bridgetown', originalRepo: 'bridgetown-main', name: 'Bridgetown Collective', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '🚀', rarity: 'epic' },
  { id: 'bridgetown-seo-tag', originalRepo: 'bridgetown-seo-tag-master', name: 'Bridgetown Seo Tag Corp', description: 'Learning documented for posterity', role: 'trophy', icon: '🔒', rarity: 'epic' },
  { id: 'btree', originalRepo: 'btree-main', name: 'Btree Factory', description: 'AI advice that is probably wrong', role: 'caddy', icon: '🐳', rarity: 'uncommon' },
  { id: 'bulletin-board', originalRepo: 'Bulletin_Board-main', name: 'Bulletin Board Collective', description: 'AI advice that is probably wrong', role: 'caddy', icon: '🔄', rarity: 'uncommon' },
  { id: 'burn-crops', originalRepo: 'burn-crops-main', name: 'Burn Crops Industries', description: 'ML predictions with confidence intervals of maybe', role: 'caddy', icon: '🌉', rarity: 'uncommon' },
  { id: 'burn-hysplitr', originalRepo: 'burn-hysplitr-main', name: 'Burn Hysplitr Co', description: 'ML predictions with confidence intervals of maybe', role: 'caddy', icon: '🖥️', rarity: 'rare' },
  { id: 'caddy-reverse-proxy', originalRepo: 'caddy-reverse-proxy-main', name: 'Caddy Reverse Proxy Ventures', description: 'DevOps chaos in a repo', role: 'hazard', icon: '🗺️', rarity: 'uncommon' },
  { id: 'calculator', originalRepo: 'calculator-main', name: 'Calculator Inc', description: 'AI advice that is probably wrong', role: 'caddy', icon: '🎨', rarity: 'common' },
  { id: 'calculators', originalRepo: 'Calculators-master', name: 'Calculators Collective', description: 'Where hot takes meet cold PRs', role: 'event', icon: '🏠', rarity: 'uncommon' },
  { id: 'calculusconnections', originalRepo: 'CalculusConnections-main', name: 'Calculusconnections Systems', description: 'ML predictions with confidence intervals of maybe', role: 'caddy', icon: '📦', rarity: 'uncommon' },
  { id: 'cams-todo-golang', originalRepo: 'cams-todo-golang-main', name: 'Cams Todo Golang Academy', description: 'The model works on my machine', role: 'caddy', icon: '🔓', rarity: 'uncommon' },
  { id: 'cam-wil', originalRepo: 'cam-wil-main', name: 'Cam Wil Systems', description: 'AI advice that is probably wrong', role: 'caddy', icon: '🔧', rarity: 'uncommon' },
  { id: 'capm-exporter', originalRepo: 'CAPM_Exporter-main', name: 'Capm Exporter Ventures', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '📈', rarity: 'uncommon' },
  { id: 'casa', originalRepo: 'casa-main', name: 'Casa Solutions', description: 'The model works on my machine', role: 'caddy', icon: '🏠', rarity: 'uncommon' },
  { id: 'clickhouse-docs', originalRepo: 'clickhouse-docs-main', name: 'Clickhouse Docs Labs', description: 'The model works on my machine', role: 'caddy', icon: '🕳️', rarity: 'legendary' },
  { id: 'clickhouse', originalRepo: 'ClickHouse-master', name: 'Analytics Warp Speed', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '🛒', rarity: 'legendary' },
  { id: 'code-puppy', originalRepo: 'code_puppy-main', name: 'Junior Dev Simulator', description: 'The model works on my machine', role: 'caddy', icon: '🌱', rarity: 'uncommon' },
  { id: 'codexjs', originalRepo: 'CodexJS-main', name: 'Codexjs Collective', description: 'The model works on my machine', role: 'caddy', icon: '📣', rarity: 'uncommon' },
  { id: 'coding-interview-university', originalRepo: 'coding-interview-university-master', name: 'LeetCode Boot Camp', description: 'From zero to one star on GitHub', role: 'milestone', icon: '🎯', rarity: 'legendary' },
  { id: 'coffee-please', originalRepo: 'coffee-please-main', name: 'Caffeine Dependency Inc', description: 'ML predictions with confidence intervals of maybe', role: 'caddy', icon: '📈', rarity: 'uncommon' },
  { id: 'conventional-comments-browser-extension', originalRepo: 'conventional-comments-browser-extension-main', name: 'Conventional Comments Browser Extension Systems', description: 'AI advice that is probably wrong', role: 'caddy', icon: '🤝', rarity: 'uncommon' },
  { id: 'coronamap', originalRepo: 'coronamap-master', name: 'Pandemic Viz Co', description: 'Communication tool for async teams', role: 'event', icon: '🎳', rarity: 'rare' },
  { id: 'counterapp', originalRepo: 'CounterApp-main', name: 'Counterapp Factory', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '📈', rarity: 'common' },
  { id: 'course-4013-wearable-ubicomp', originalRepo: 'Course_4013_Wearable-Ubicomp-master', name: 'Course 4013 Wearable Ubicomp LLC', description: 'Academic achievement unlocked', role: 'milestone', icon: '🗺️', rarity: 'uncommon' },
  { id: 'course-4813-computergraphics', originalRepo: 'Course_4813_ComputerGraphics-master', name: 'Course 4813 Computergraphics Solutions', description: 'Completed coursework that proves effort', role: 'milestone', icon: '💧', rarity: 'uncommon' },
  { id: 'course-csce3613-operatingsystems', originalRepo: 'Course_CSCE3613_OperatingSystems-master', name: 'Course Csce3613 Operatingsystems Academy', description: 'Completed coursework that proves effort', role: 'milestone', icon: '🔗', rarity: 'uncommon' },
  { id: 'cover-crop-rotation', originalRepo: 'cover-crop-rotation-main', name: 'Cover Crop Rotation Ventures', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '🗺️', rarity: 'uncommon' },
  { id: 'covid19-symptom-tracker', originalRepo: 'covid19-symptom-tracker-master', name: 'Covid19 Symptom Tracker Industries', description: 'They ship while we debate tabs vs spaces', role: 'competitor', icon: '💵', rarity: 'legendary' },
  { id: 'cs50-pset3', originalRepo: 'cs50-pset3-master', name: 'Cs50 Pset3 Factory', description: 'Completed coursework that proves effort', role: 'milestone', icon: '⚖️', rarity: 'common' },
  { id: 'cs50-pset4', originalRepo: 'cs50-pset4-master', name: 'Cs50 Pset4 Collective', description: 'Learning projects as trophies', role: 'milestone', icon: '🐛', rarity: 'common' },
  { id: 'cs50-pset5', originalRepo: 'cs50-pset5-master', name: 'Cs50 Pset5 Ventures', description: 'From zero to one star on GitHub', role: 'milestone', icon: '📣', rarity: 'common' },
  { id: 'cs50-pset6', originalRepo: 'cs50-pset6-master', name: 'Cs50 Pset6 Inc', description: 'Academic achievement unlocked', role: 'milestone', icon: '🌉', rarity: 'common' },
  { id: 'cs50-pset7', originalRepo: 'cs50-pset7-master', name: 'Cs50 Pset7 Co', description: 'Completed coursework that proves effort', role: 'milestone', icon: '🔄', rarity: 'common' },
  { id: 'cs50-pset8', originalRepo: 'cs50-pset8-master', name: 'Cs50 Pset8 Labs', description: 'Learning projects as trophies', role: 'milestone', icon: '🐦', rarity: 'common' },
  { id: 'csc521', originalRepo: 'csc521-master', name: 'Csc521 Factory', description: 'The tool you did not know you needed', role: 'powerup', icon: '🔗', rarity: 'uncommon' },
  { id: 'csce2214', originalRepo: 'csce2214-main', name: 'Csce2214 LLC', description: 'ML predictions with confidence intervals of maybe', role: 'caddy', icon: '🏢', rarity: 'uncommon' },
  { id: 'csharp-ceramics', originalRepo: 'CSharp_Ceramics-main', name: 'Csharp Ceramics LLC', description: 'ML predictions with confidence intervals of maybe', role: 'caddy', icon: '🏢', rarity: 'uncommon' },
  { id: 'cstc210', originalRepo: 'cstc210-main', name: 'Cstc210 LLC', description: 'The model works on my machine', role: 'caddy', icon: '🎯', rarity: 'uncommon' },
  { id: 'cuspatial-branch-25-04', originalRepo: 'cuspatial-branch-25.04', name: 'Cuspatial Branch 25 04 Labs', description: 'They ship while we debate tabs vs spaces', role: 'competitor', icon: '🎳', rarity: 'epic' },
  { id: 'cypress', originalRepo: 'cypress-develop', name: 'E2E Anxiety Reducer', description: 'Helper code that actually helps', role: 'powerup', icon: '🎓', rarity: 'legendary' },
  { id: 'cypress-documentation', originalRepo: 'cypress-documentation-master', name: 'Cypress Documentation Co', description: 'Helper code that actually helps', role: 'powerup', icon: '⚡', rarity: 'uncommon' },
  { id: 'dave', originalRepo: 'dave-main', name: 'Dave Inc', description: 'The model works on my machine', role: 'caddy', icon: '💰', rarity: 'uncommon' },
  { id: 'deedy-resume', originalRepo: 'Deedy-Resume-master', name: 'LaTeX LinkedIn', description: 'One domain to rule them all', role: 'sponsor', icon: '🌐', rarity: 'legendary' },
  { id: 'deepforest-vim', originalRepo: 'deepforest.vim-master', name: 'Deepforest Vim Academy', description: 'Microservices for a TODO app', role: 'employee', icon: '📣', rarity: 'uncommon' },
  { id: 'deepforest-zsh-theme', originalRepo: 'deepforest.zsh-theme-master', name: 'Deepforest Zsh Theme Academy', description: 'Middleware that middleware middlewares', role: 'employee', icon: '📈', rarity: 'uncommon' },
  { id: 'deno', originalRepo: 'deno-main', name: 'Node Revenge Arc', description: 'AI advice that is probably wrong', role: 'caddy', icon: '🐳', rarity: 'legendary' },
  { id: 'det030-website-2013', originalRepo: 'Det030_Website_2013-main', name: 'Det030 Website 2013 Ventures', description: 'Personal branding as a service', role: 'sponsor', icon: '🏆', rarity: 'uncommon' },
  { id: 'dev-to', originalRepo: 'dev.to-main', name: 'Dev To Systems', description: 'The model works on my machine', role: 'caddy', icon: '🎲', rarity: 'uncommon' },
  { id: 'dev-to-2', originalRepo: 'dev.to-master', name: 'Dev To Systems', description: 'Middleware that middleware middlewares', role: 'employee', icon: '📰', rarity: 'uncommon' },
  { id: 'djangoapi', originalRepo: 'djangoapi-master', name: 'Djangoapi Solutions', description: 'API responses and existential dread', role: 'employee', icon: '💰', rarity: 'uncommon' },
  { id: 'django-learning', originalRepo: 'Django-Learning-master', name: 'Django Learning Ventures', description: 'Middleware that middleware middlewares', role: 'employee', icon: '📰', rarity: 'uncommon' },
  { id: 'djangoweather', originalRepo: 'djangoweather-master', name: 'Djangoweather Co', description: 'Microservices for a TODO app', role: 'employee', icon: '🐳', rarity: 'uncommon' },
  { id: 'docs', originalRepo: 'docs-develop', name: 'Docs Studios', description: 'Development setup as identity', role: 'equipment', icon: '📈', rarity: 'uncommon' },
  { id: 'drumpractice', originalRepo: 'DrumPractice-main', name: 'Rhythm Retention Labs', description: 'ML predictions with confidence intervals of maybe', role: 'caddy', icon: '🏆', rarity: 'uncommon' },
  { id: 'dummyweb', originalRepo: 'dummyweb-main', name: 'Dummyweb Corp', description: 'AI advice that is probably wrong', role: 'caddy', icon: '🔄', rarity: 'common' },
  { id: 'earthengine', originalRepo: 'EarthEngine-master', name: 'Earthengine Solutions', description: 'The minigame the standup needed', role: 'minigame', icon: '☕', rarity: 'uncommon' },
  { id: 'ec525s19', originalRepo: 'EC525S19-master', name: 'Ec525s19 Solutions', description: 'Click things until something happens', role: 'minigame', icon: '🔄', rarity: 'uncommon' },
  { id: 'e-commerce-template', originalRepo: 'E-Commerce_Template-main', name: 'E Commerce Template Studios', description: 'The model works on my machine', role: 'caddy', icon: '🤝', rarity: 'uncommon' },
  { id: 'ecommerce-admin', originalRepo: 'ecommerce-admin-main', name: 'Ecommerce Admin Labs', description: 'AI advice that is probably wrong', role: 'caddy', icon: '🎲', rarity: 'uncommon' },
  { id: 'e-commerce', originalRepo: 'e-commerce-main', name: 'E Commerce Co', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '💵', rarity: 'uncommon' },
  { id: 'edgeguides', originalRepo: 'edgeguides-main', name: 'Edgeguides Systems', description: 'AI advice that is probably wrong', role: 'caddy', icon: '🎮', rarity: 'uncommon' },
  { id: 'elevationproject', originalRepo: 'ElevationProject-master', name: 'Elevationproject Factory', description: 'Boosts velocity by 2x maybe', role: 'powerup', icon: '🎳', rarity: 'uncommon' },
  { id: 'emr', originalRepo: 'emr-master', name: 'Emr Ventures', description: 'Learning projects as trophies', role: 'milestone', icon: '🚢', rarity: 'uncommon' },
  { id: 'engl353', originalRepo: 'engl353-main', name: 'Engl353 Solutions', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '🐍', rarity: 'uncommon' },
  { id: 'epsilon', originalRepo: 'epsilon-main', name: 'Epsilon Industries', description: 'AI advice that is probably wrong', role: 'caddy', icon: '⚖️', rarity: 'uncommon' },
  { id: 'etch-a-sketch', originalRepo: 'etch-a-sketch-master', name: 'Nostalgia Tech Labs', description: 'React patterns and regret patterns', role: 'course', icon: '⚛️', rarity: 'common' },
  { id: 'ethanzitting-com', originalRepo: 'ethanzitting.com-main', name: 'Ethanzitting Com Solutions', description: 'AI advice that is probably wrong', role: 'caddy', icon: '🧪', rarity: 'uncommon' },
  { id: 'evosnake', originalRepo: 'evosnake-master', name: 'Evolutionary Game Theory', description: 'Playable distraction from real code', role: 'minigame', icon: '🐦', rarity: 'uncommon' },
  { id: 'example-construction-site', originalRepo: 'example-construction-site-main', name: 'Example Construction Site Collective', description: 'AI advice that is probably wrong', role: 'caddy', icon: '⚖️', rarity: 'uncommon' },
  { id: 'explodingkittens', originalRepo: 'ExplodingKittens-main', name: 'Chaos Cat Ventures', description: 'Click things until something happens', role: 'minigame', icon: '💧', rarity: 'rare' },
  { id: 'express-hateoas-links', originalRepo: 'express-hateoas-links-master', name: 'Express Hateoas Links Studios', description: 'Backend so powerful nobody uses it', role: 'employee', icon: '🌉', rarity: 'rare' },
  { id: 'extremes', originalRepo: 'extRemes-master', name: 'Extremes Systems', description: 'One domain to rule them all', role: 'sponsor', icon: '🧪', rarity: 'uncommon' },
  { id: 'facebook-auto-like', originalRepo: 'facebook-auto-like-master', name: 'Facebook Auto Like Factory', description: 'Boosts velocity by 2x maybe', role: 'powerup', icon: '🐦', rarity: 'uncommon' },
  { id: 'faker', originalRepo: 'faker-master', name: 'Fake Data Factory', description: 'The tool you did not know you needed', role: 'powerup', icon: '🧪', rarity: 'epic' },
  { id: 'fbla-csa', originalRepo: 'fbla-csa-master', name: 'Fbla Csa Academy', description: 'API responses and existential dread', role: 'employee', icon: '🎮', rarity: 'uncommon' },
  { id: 'feed', originalRepo: 'feed-master', name: 'Feed Co', description: 'Communication tool for async teams', role: 'event', icon: '📝', rarity: 'uncommon' },
  { id: 'fetching-apis', originalRepo: 'fetching_apis-main', name: 'Fetching Apis Co', description: 'API responses and existential dread', role: 'employee', icon: '🔓', rarity: 'common' },
  { id: 'fidget-widget', originalRepo: 'fidget-widget-master', name: 'Fidget Widget Corp', description: 'Proof of concept proof of effort', role: 'trophy', icon: '📊', rarity: 'uncommon' },
  { id: 'file-manager-graphql-api', originalRepo: 'file_manager_graphql_api-main', name: 'File Manager Graphql Api Academy', description: 'Backend so powerful nobody uses it', role: 'employee', icon: '📰', rarity: 'uncommon' },
  { id: 'finalproject', originalRepo: 'finalproject-master', name: 'Finalproject Academy', description: 'API responses and existential dread', role: 'employee', icon: '🌱', rarity: 'uncommon' },
  { id: 'firebase-react-authentication', originalRepo: 'firebase-react-authentication-master', name: 'Firebase React Authentication Corp', description: 'UI library showcase', role: 'course', icon: '📈', rarity: 'uncommon' },
  { id: 'firstandroidtest', originalRepo: 'firstandroidtest-master', name: 'Firstandroidtest Industries', description: 'The tool you did not know you needed', role: 'powerup', icon: '🕳️', rarity: 'common' },
  { id: 'firstreactproject', originalRepo: 'FirstReactProject-master', name: 'Firstreactproject Solutions', description: 'UI library showcase', role: 'course', icon: '🖥️', rarity: 'common' },
  { id: 'first-spring-project', originalRepo: 'First-Spring-Project-master', name: 'First Spring Project Systems', description: 'Middleware that middleware middlewares', role: 'employee', icon: '📊', rarity: 'common' },
  { id: 'fish', originalRepo: 'fish-master', name: 'Shell Enthusiast Society', description: 'Boosts velocity by 2x maybe', role: 'powerup', icon: '🌉', rarity: 'legendary' },
  { id: 'flapbird', originalRepo: 'FLAPBIRD-master', name: 'Viral Clone Industries', description: 'Playable distraction from real code', role: 'minigame', icon: '🔥', rarity: 'uncommon' },
  { id: 'flaskapp-template', originalRepo: 'flaskapp-template-master', name: 'Flaskapp Template Inc', description: 'Microservices for a TODO app', role: 'employee', icon: '🌐', rarity: 'uncommon' },
  { id: 'flaskdeveloperwebsite', originalRepo: 'flaskDeveloperWebsite-main', name: 'Flaskdeveloperwebsite Co', description: 'Our portfolio site has better uptime than our product', role: 'sponsor', icon: '📰', rarity: 'uncommon' },
  { id: 'flowable-springboot', originalRepo: 'Flowable-SpringBoot-main', name: 'Flowable Springboot Industries', description: 'API responses and existential dread', role: 'employee', icon: '🎲', rarity: 'rare' },
  { id: 'fluke', originalRepo: 'fluke-main', name: 'Fluke Labs', description: 'ML predictions with confidence intervals of maybe', role: 'caddy', icon: '💻', rarity: 'uncommon' },
  { id: 'forem-browser-extension', originalRepo: 'forem-browser-extension-master', name: 'Forem Browser Extension Studios', description: 'Infrastructure anxiety as a feature', role: 'hazard', icon: '🎓', rarity: 'uncommon' },
  { id: 'fourier', originalRepo: 'fourier-master', name: 'Fourier Factory', description: 'Helper code that actually helps', role: 'powerup', icon: '🐱', rarity: 'uncommon' },
  { id: 'fundamentals', originalRepo: 'fundamentals-main', name: 'Fundamentals Industries', description: 'AI advice that is probably wrong', role: 'caddy', icon: '🎨', rarity: 'common' },
  { id: 'game1', originalRepo: 'Game1-master', name: 'Indie Game Studio Alpha', description: 'Another game we built instead of working', role: 'minigame', icon: '🔄', rarity: 'uncommon' },
  { id: 'game-of-life', originalRepo: 'game-of-life-master', name: 'Conway Corporate Sim', description: 'Click things until something happens', role: 'minigame', icon: '🔄', rarity: 'uncommon' },
  { id: 'gcs-rs', originalRepo: 'gcs-rs-main', name: 'Gcs Rs Systems', description: 'ML predictions with confidence intervals of maybe', role: 'caddy', icon: '🚀', rarity: 'uncommon' },
  { id: 'gifmaker', originalRepo: 'gifmaker-main', name: 'Gifmaker Systems', description: 'AI advice that is probably wrong', role: 'caddy', icon: '🤖', rarity: 'uncommon' },
  { id: 'giphy-clone', originalRepo: 'giphy-clone-main', name: 'Giphy Clone Co', description: 'Built our product as a side project', role: 'competitor', icon: '📦', rarity: 'uncommon' },
  { id: 'githubgraduation-2021', originalRepo: 'GitHubGraduation-2021-main', name: 'Githubgraduation 2021 Solutions', description: 'ML predictions with confidence intervals of maybe', role: 'caddy', icon: '🐱', rarity: 'uncommon' },
  { id: 'githubgraduation-2022', originalRepo: 'GitHubGraduation-2022-main', name: 'Githubgraduation 2022 Systems', description: 'The model works on my machine', role: 'caddy', icon: '🕳️', rarity: 'uncommon' },
  { id: 'githug', originalRepo: 'githug-master', name: 'Githug Collective', description: 'Communication tool for async teams', role: 'event', icon: '🚢', rarity: 'uncommon' },
  { id: 'goodwatch', originalRepo: 'goodwatch-master', name: 'Goodwatch Collective', description: 'Communication tool for async teams', role: 'event', icon: '🎳', rarity: 'uncommon' },
  { id: 'google-homepage', originalRepo: 'google-homepage-master', name: 'Google Homepage Ventures', description: 'Learning projects as trophies', role: 'milestone', icon: '🐱', rarity: 'common' },
  { id: 'governance-deforestation', originalRepo: 'governance_deforestation-main', name: 'Governance Deforestation Ventures', description: 'Microservices for a TODO app', role: 'employee', icon: '🎮', rarity: 'uncommon' },
  { id: 'grab-user', originalRepo: 'grab_user-master', name: 'Grab User Academy', description: 'The minigame the standup needed', role: 'minigame', icon: '🚀', rarity: 'uncommon' },
  { id: 'grafana', originalRepo: 'grafana-main', name: 'Dashboard Decadence Inc', description: 'The model works on my machine', role: 'caddy', icon: '🎉', rarity: 'legendary' },
  { id: 'grape', originalRepo: 'grape-master', name: 'Grape Academy', description: 'Microservices for a TODO app', role: 'employee', icon: '💧', rarity: 'epic' },
  { id: 'gsodr', originalRepo: 'GSODR-master', name: 'Gsodr Factory', description: 'Utility functions that save the day', role: 'powerup', icon: '🎮', rarity: 'uncommon' },
  { id: 'hackathon-2023', originalRepo: 'Hackathon-2023-main', name: 'Hackathon 2023 Systems', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '🐱', rarity: 'uncommon' },
  { id: 'heroku-craft-site', originalRepo: 'heroku-craft-site-main', name: 'Heroku Craft Site Systems', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '📊', rarity: 'uncommon' },
  { id: 'hha-grades', originalRepo: 'hha-grades-master', name: 'Hha Grades Solutions', description: 'Playable distraction from real code', role: 'minigame', icon: '🐱', rarity: 'uncommon' },
  { id: 'hiragana-katakana-randomizer', originalRepo: 'Hiragana-Katakana-Randomizer-master', name: 'Script Shuffle Inc', description: 'Middleware that middleware middlewares', role: 'employee', icon: '🎵', rarity: 'uncommon' },
  { id: 'homeaccesschecker', originalRepo: 'HomeAccessChecker-master', name: 'Homeaccesschecker Industries', description: 'Built our product as a side project', role: 'competitor', icon: '🏢', rarity: 'uncommon' },
  { id: 'houseapp', originalRepo: 'HouseApp-master', name: 'Houseapp Collective', description: 'Where hot takes meet cold PRs', role: 'event', icon: '🔄', rarity: 'uncommon' },
  { id: 'httplogger', originalRepo: 'httplogger-master', name: 'Httplogger Studios', description: 'Infrastructure anxiety as a feature', role: 'hazard', icon: '🐱', rarity: 'uncommon' },
  { id: 'hubspot-api-aggregator', originalRepo: 'hubspot_api_aggregator-main', name: 'Hubspot Api Aggregator Inc', description: 'API responses and existential dread', role: 'employee', icon: '🔓', rarity: 'uncommon' },
  { id: 'hubspot-api-nodejs', originalRepo: 'hubspot-api-nodejs-master', name: 'Hubspot Api Nodejs Inc', description: 'Middleware that middleware middlewares', role: 'employee', icon: '📈', rarity: 'uncommon' },
  { id: 'hubspot-cli', originalRepo: 'hubspot-cli-master', name: 'Hubspot Cli Ventures', description: 'Academic achievement unlocked', role: 'milestone', icon: '🐦', rarity: 'uncommon' },
  { id: 'human-essentials', originalRepo: 'human-essentials-main', name: 'Human Essentials Co', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '🛒', rarity: 'uncommon' },
  { id: 'imagery-downloaders', originalRepo: 'imagery-downloaders-main', name: 'Imagery Downloaders Solutions', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '🐍', rarity: 'uncommon' },
  { id: 'indie-stack', originalRepo: 'indie-stack-main', name: 'Solo Founder Stack', description: 'The model works on my machine', role: 'caddy', icon: '🎮', rarity: 'epic' },
  { id: 'indie-stack-test', originalRepo: 'indie-stack-test-main', name: 'Indie Stack Test Academy', description: 'Boosts velocity by 2x maybe', role: 'powerup', icon: '🎓', rarity: 'epic' },
  { id: 'indo', originalRepo: 'indo-main', name: 'Indo Factory', description: 'AI advice that is probably wrong', role: 'caddy', icon: '🔗', rarity: 'uncommon' },
  { id: 'interactivestory', originalRepo: 'InteractiveStory-master', name: 'Branching Narrative Labs', description: 'Config files as personality', role: 'equipment', icon: '🎯', rarity: 'uncommon' },
  { id: 'intermediatereact', originalRepo: 'IntermediateReact-main', name: 'Intermediatereact Industries', description: 'AI advice that is probably wrong', role: 'caddy', icon: '🔄', rarity: 'uncommon' },
  { id: 'irb', originalRepo: 'irb-master', name: 'Ruby REPL Republic', description: 'Click things until something happens', role: 'minigame', icon: '📣', rarity: 'legendary' },
  { id: 'iseven', originalRepo: 'isEven-master', name: 'Parity Checking Inc', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '📦', rarity: 'uncommon' },
  { id: 'jack-snake', originalRepo: 'jack-snake-main', name: 'Classic Game Remix Co', description: 'Click things until something happens', role: 'minigame', icon: '🤝', rarity: 'uncommon' },
  { id: 'java3d', originalRepo: 'Java3D-master', name: 'Java3d Factory', description: 'The tool you did not know you needed', role: 'powerup', icon: '🔧', rarity: 'uncommon' },
  { id: 'javacourse', originalRepo: 'JavaCourse-main', name: 'Javacourse Studios', description: 'Learning projects as trophies', role: 'milestone', icon: '📦', rarity: 'uncommon' },
  { id: 'java-jwt-authentication', originalRepo: 'java-jwt-authentication-main', name: 'Java Jwt Authentication Inc', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '🏆', rarity: 'uncommon' },
  { id: 'javascript-tc-workshop', originalRepo: 'JavaScript-TC-Workshop-main', name: 'Javascript Tc Workshop Labs', description: 'Academic achievement unlocked', role: 'milestone', icon: '🐦', rarity: 'common' },
  { id: 'jbhts19-server', originalRepo: 'JBHTS19_server-master', name: 'Jbhts19 Server Co', description: 'Microservices for a TODO app', role: 'employee', icon: '👥', rarity: 'uncommon' },
  { id: 'jets', originalRepo: 'jets-master', name: 'Jets Studios', description: 'DevOps chaos in a repo', role: 'hazard', icon: '🏢', rarity: 'epic' },
  { id: 'jira-cli-app', originalRepo: 'jira-cli-app-main', name: 'Jira Cli App Co', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '🐦', rarity: 'uncommon' },
  { id: 'jira-github-action-integration-demo', originalRepo: 'jira-github-action-integration-demo-master', name: 'Jira Github Action Integration Demo Industries', description: 'Built our product as a side project', role: 'competitor', icon: '🚀', rarity: 'uncommon' },
  { id: 'jsanker-org', originalRepo: 'jsanker.org-main', name: 'Jsanker Org Solutions', description: 'The model works on my machine', role: 'caddy', icon: '🐳', rarity: 'uncommon' },
  { id: 'js-design-patterns', originalRepo: 'JS-Design-Patterns-main', name: 'Js Design Patterns Systems', description: 'AI advice that is probably wrong', role: 'caddy', icon: '🕳️', rarity: 'uncommon' },
  { id: 'js-paddle-game', originalRepo: 'JS-Paddle-Game-master', name: 'Pong Revival Studios', description: 'Another game we built instead of working', role: 'minigame', icon: '💰', rarity: 'uncommon' },
  { id: 'kratos-fork', originalRepo: 'kratos-fork-master', name: 'Kratos Fork Industries', description: 'They pivoted to our exact idea', role: 'competitor', icon: '🎮', rarity: 'uncommon' },
  { id: 'laravel-boilerplate', originalRepo: 'laravel-boilerplate-main', name: 'Laravel Boilerplate Studios', description: 'ML predictions with confidence intervals of maybe', role: 'caddy', icon: '🚢', rarity: 'epic' },
  { id: 'ldap-connector', originalRepo: 'LDAP-Connector-master', name: 'Ldap Connector Corp', description: 'The repo that got a star', role: 'trophy', icon: '📱', rarity: 'uncommon' },
  { id: 'learn-go-with-tests', originalRepo: 'learn-go-with-tests-master', name: 'Learn Go With Tests Co', description: 'Boosts velocity by 2x maybe', role: 'powerup', icon: '🐦', rarity: 'uncommon' },
  { id: 'leetcode-in-go', originalRepo: 'leetcode-in-go-main', name: 'Leetcode In Go LLC', description: 'From zero to one star on GitHub', role: 'milestone', icon: '⚖️', rarity: 'uncommon' },
  { id: 'lfgo', originalRepo: 'LFGo-main', name: 'Lfgo Industries', description: 'The model works on my machine', role: 'caddy', icon: '❌', rarity: 'uncommon' },
  { id: 'libcloud', originalRepo: 'libcloud-trunk', name: 'Libcloud Co', description: 'SDK for the SDK wrapper', role: 'equipment', icon: '💵', rarity: 'uncommon' },
  { id: 'library-app', originalRepo: 'library-app-main', name: 'Library App Solutions', description: 'ML predictions with confidence intervals of maybe', role: 'caddy', icon: '🔒', rarity: 'uncommon' },
  { id: 'lmtest', originalRepo: 'lmtest-master', name: 'Lmtest Labs', description: 'The tool you did not know you needed', role: 'powerup', icon: '⌨️', rarity: 'common' },
  { id: 'lovefern', originalRepo: 'lovefern-main', name: 'Houseplant Parent Guilt', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '🔥', rarity: 'uncommon' },
  { id: 'lukebrandon-github-io', originalRepo: 'lukebrandon.github.io-master', name: 'Lukebrandon Github Io Corp', description: 'Personal branding as a service', role: 'sponsor', icon: '☕', rarity: 'uncommon' },
  { id: 'lukebrandon', originalRepo: 'LukeBrandon-master', name: 'Lukebrandon Corp', description: 'One domain to rule them all', role: 'sponsor', icon: '🐳', rarity: 'uncommon' },
  { id: 'macbook-home-config', originalRepo: 'macbook-home-config-main', name: 'Macbook Home Config Solutions', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '📝', rarity: 'uncommon' },
  { id: 'madmin', originalRepo: 'madmin-master', name: 'Madmin Systems', description: 'Resume but make it interactive', role: 'sponsor', icon: '🚀', rarity: 'uncommon' },
  { id: 'maptiler-sdk-js-fork', originalRepo: 'maptiler-sdk-js-fork-main', name: 'Maptiler Sdk Js Fork Collective', description: 'They pivoted to our exact idea', role: 'competitor', icon: '🏠', rarity: 'uncommon' },
  { id: 'mdb-report-helper', originalRepo: 'mdb-report-helper-main', name: 'Mdb Report Helper Labs', description: 'Boosts velocity by 2x maybe', role: 'powerup', icon: '🏆', rarity: 'uncommon' },
  { id: 'mern-memories', originalRepo: 'Mern_Memories-main', name: 'Mern Memories Solutions', description: 'AI advice that is probably wrong', role: 'caddy', icon: '🔧', rarity: 'rare' },
  { id: 'mernlocationsharingapp', originalRepo: 'MERNLocationSharingApp-master', name: 'Mernlocationsharingapp Academy', description: 'Middleware that middleware middlewares', role: 'employee', icon: '🛒', rarity: 'rare' },
  { id: 'model', originalRepo: 'model-main', name: 'Black Box Confidence Co', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '🔒', rarity: 'uncommon' },
  { id: 'modern-aw-game', originalRepo: 'modern-aw-game-main', name: 'Retro Awkwardness Sim', description: 'The minigame the standup needed', role: 'minigame', icon: '🐦', rarity: 'rare' },
  { id: 'morenode', originalRepo: 'MoreNode-main', name: 'Morenode Ventures', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '🐍', rarity: 'uncommon' },
  { id: 'movie-maker', originalRepo: 'movie-maker-master', name: 'Movie Maker Ventures', description: 'From zero to one star on GitHub', role: 'milestone', icon: '🎲', rarity: 'uncommon' },
  { id: 'mq-dev-patterns', originalRepo: 'mq-dev-patterns-master', name: 'Mq Dev Patterns LLC', description: 'Development setup as identity', role: 'equipment', icon: '🚢', rarity: 'uncommon' },
  { id: 'music-writer', originalRepo: 'music-writer-master', name: 'Music Writer Collective', description: 'Social coding in the wild', role: 'event', icon: '⌨️', rarity: 'rare' },
  { id: 'myneat', originalRepo: 'MyNEAT-main', name: 'Neuroevolution Labs', description: 'AI advice that is probably wrong', role: 'caddy', icon: '📣', rarity: 'uncommon' },
  { id: 'native-stuff', originalRepo: 'native-stuff-main', name: 'Native Stuff Studios', description: 'The model works on my machine', role: 'caddy', icon: '💧', rarity: 'uncommon' },
  { id: 'neon-control-plane', originalRepo: 'neon_control_plane-main', name: 'Neon Control Plane Ventures', description: 'Infrastructure anxiety as a feature', role: 'hazard', icon: '🖥️', rarity: 'epic' },
  { id: 'neon', originalRepo: 'neon-main', name: 'Postgres On Steroids', description: 'YAML nightmares and config drift', role: 'hazard', icon: '🌱', rarity: 'epic' },
  { id: 'neural-net', originalRepo: 'neural-net-master', name: 'Gradient Descent Co', description: 'AI advice that is probably wrong', role: 'caddy', icon: '📣', rarity: 'uncommon' },
  { id: 'newsbadger', originalRepo: 'newsbadger-master', name: 'Newsbadger Solutions', description: 'Engagement is our growth metric', role: 'event', icon: '🎵', rarity: 'uncommon' },
  { id: 'next-enterprise', originalRepo: 'next-enterprise-main', name: 'Next Enterprise Industries', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '🚢', rarity: 'epic' },
  { id: 'nextjs-dashboard', originalRepo: 'nextjs-dashboard-main', name: 'Nextjs Dashboard Collective', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '🖥️', rarity: 'uncommon' },
  { id: 'nextjs-live-transcription', originalRepo: 'nextjs-live-transcription-main', name: 'Nextjs Live Transcription Co', description: 'AI advice that is probably wrong', role: 'caddy', icon: '⚛️', rarity: 'uncommon' },
  { id: 'nextjs-twitter-clone', originalRepo: 'nextjs-twitter-clone-main', name: 'X But With Character', description: 'They pivoted to our exact idea', role: 'competitor', icon: '⚛️', rarity: 'uncommon' },
  { id: 'next-website', originalRepo: 'next-website-main', name: 'Next Website Ventures', description: 'Personal branding as a service', role: 'sponsor', icon: '🗺️', rarity: 'uncommon' },
  { id: 'nmachine', originalRepo: 'nmachine-main', name: 'Nmachine Corp', description: 'ML predictions with confidence intervals of maybe', role: 'caddy', icon: '⚡', rarity: 'uncommon' },
  { id: 'nwacc', originalRepo: 'NWACC-main', name: 'Nwacc LLC', description: 'The model works on my machine', role: 'caddy', icon: '🎨', rarity: 'uncommon' },
  { id: 'nwarkansas-developers-guide', originalRepo: 'NWArkansas-Developers-Guide-master', name: 'Nwarkansas Developers Guide Studios', description: 'DevOps chaos in a repo', role: 'hazard', icon: '📝', rarity: 'uncommon' },
  { id: 'okapi', originalRepo: 'okapi-master', name: 'Okapi Ventures', description: 'Middleware that middleware middlewares', role: 'employee', icon: '🐛', rarity: 'epic' },
  { id: 'omnifood-project', originalRepo: 'Omnifood-Project-main', name: 'Omnifood Project Ventures', description: 'ML predictions with confidence intervals of maybe', role: 'caddy', icon: '☕', rarity: 'uncommon' },
  { id: 'onuris-ftc', originalRepo: 'onuris-ftc-master', name: 'Onuris Ftc Academy', description: 'Backend so powerful nobody uses it', role: 'employee', icon: '🐱', rarity: 'rare' },
  { id: 'openchat', originalRepo: 'openchat-master', name: 'Openchat Solutions', description: 'Engagement is our growth metric', role: 'event', icon: '🔥', rarity: 'rare' },
  { id: 'opengeohub2020', originalRepo: 'OpenGeoHub2020-master', name: 'Opengeohub2020 Corp', description: 'Proof of concept proof of effort', role: 'trophy', icon: '💻', rarity: 'uncommon' },
  { id: 'openwrt-n6260', originalRepo: 'openwrt-N6260-main', name: 'Openwrt N6260 Inc', description: 'YAML nightmares and config drift', role: 'hazard', icon: '⌨️', rarity: 'uncommon' },
  { id: 'owning-rails', originalRepo: 'owning-rails-master', name: 'Owning Rails Academy', description: 'Backend so powerful nobody uses it', role: 'employee', icon: '🚢', rarity: 'uncommon' },
  { id: 'pay', originalRepo: 'pay-master', name: 'Pay Solutions', description: 'The minigame the standup needed', role: 'minigame', icon: '🏢', rarity: 'uncommon' },
  { id: 'personalpage', originalRepo: 'PersonalPage-master', name: 'Personalpage Academy', description: 'One domain to rule them all', role: 'sponsor', icon: '🐳', rarity: 'uncommon' },
  { id: 'personal-portfolio-v2', originalRepo: 'Personal-Portfolio-V2-main', name: 'Personal Portfolio V2 Factory', description: 'One domain to rule them all', role: 'sponsor', icon: '⚛️', rarity: 'uncommon' },
  { id: 'personal-website', originalRepo: 'personal-website-main', name: 'Personal Website LLC', description: 'One domain to rule them all', role: 'sponsor', icon: '🔗', rarity: 'uncommon' },
  { id: 'phonegap-plugin-barcodescanner', originalRepo: 'phonegap-plugin-barcodescanner-master', name: 'Phonegap Plugin Barcodescanner Systems', description: 'One domain to rule them all', role: 'sponsor', icon: '🎲', rarity: 'uncommon' },
  { id: 'photon-main', originalRepo: 'photon-main-main', name: 'Photon Main Ventures', description: 'AI advice that is probably wrong', role: 'caddy', icon: '🧪', rarity: 'epic' },
  { id: 'pinteresting', originalRepo: 'pinteresting-master', name: 'Pinteresting Industries', description: 'Middleware that middleware middlewares', role: 'employee', icon: '🎓', rarity: 'uncommon' },
  { id: 'plane-notify-multi', originalRepo: 'plane-notify-multi', name: 'Plane Notify Multi Solutions', description: 'The tool you did not know you needed', role: 'powerup', icon: '⚛️', rarity: 'uncommon' },
  { id: 'pocket-casts-android', originalRepo: 'pocket-casts-android-main', name: 'Pocket Casts Android Inc', description: 'ML predictions with confidence intervals of maybe', role: 'caddy', icon: '💵', rarity: 'common' },
  { id: 'poker', originalRepo: 'poker-master', name: 'All In Simulator', description: 'Click things until something happens', role: 'minigame', icon: '🎮', rarity: 'rare' },
  { id: 'poodr', originalRepo: 'POODR-master', name: 'Poodr Labs', description: 'The project that could have been a startup', role: 'clubhouse', icon: '⚡', rarity: 'uncommon' },
  { id: 'portfolio-v2', originalRepo: 'portfolio-v2-main', name: 'Portfolio V2 Academy', description: 'Personal branding as a service', role: 'sponsor', icon: '🚢', rarity: 'uncommon' },
  { id: 'portfolio-v3', originalRepo: 'portfolio-v3-main', name: 'Portfolio V3 Industries', description: 'One domain to rule them all', role: 'sponsor', icon: '👥', rarity: 'uncommon' },
  { id: 'portfolio-website', originalRepo: 'Portfolio-Website-master', name: 'Portfolio Website Studios', description: 'Resume but make it interactive', role: 'sponsor', icon: '📰', rarity: 'uncommon' },
  { id: 'postcard', originalRepo: 'postcard-master', name: 'Postcard Systems', description: 'Personal branding as a service', role: 'sponsor', icon: '🚢', rarity: 'uncommon' },
  { id: 'posthog-com', originalRepo: 'posthog.com-master', name: 'Posthog Com Solutions', description: 'One domain to rule them all', role: 'sponsor', icon: '🎉', rarity: 'legendary' },
  { id: 'posthog', originalRepo: 'posthog-master', name: 'Open Source Surveillance Co', description: 'Playable distraction from real code', role: 'minigame', icon: '🏆', rarity: 'legendary' },
  { id: 'probabilistic-rating-engine', originalRepo: 'Probabilistic-Rating-Engine-main', name: 'Probabilistic Rating Engine Solutions', description: 'The model works on my machine', role: 'caddy', icon: '⚖️', rarity: 'uncommon' },
  { id: 'programming-club', originalRepo: 'programming-club-master', name: 'Programming Club Corp', description: 'Learning documented for posterity', role: 'trophy', icon: '💻', rarity: 'uncommon' },
  { id: 'programming-paradigms', originalRepo: 'Programming-Paradigms-main', name: 'Programming Paradigms Inc', description: 'From zero to one star on GitHub', role: 'milestone', icon: '🔓', rarity: 'uncommon' },
  { id: 'programming-paradigms-2', originalRepo: 'Programming-Paradigms-master', name: 'Programming Paradigms Inc', description: 'Learning projects as trophies', role: 'milestone', icon: '🖥️', rarity: 'uncommon' },
  { id: 'project-cid', originalRepo: 'Project_CID-main', name: 'Project Cid Corp', description: 'AI advice that is probably wrong', role: 'caddy', icon: '❌', rarity: 'uncommon' },
  { id: 'puffyboa-xyz', originalRepo: 'puffyboa.xyz-master', name: 'Puffyboa Xyz Academy', description: 'Same concept better funding', role: 'competitor', icon: '🌐', rarity: 'uncommon' },
  { id: 'puma', originalRepo: 'puma-master', name: 'Ruby Web Server Dynasty', description: 'Our portfolio site has better uptime than our product', role: 'sponsor', icon: '🎉', rarity: 'legendary' },
  { id: 'pyalarmdotcom', originalRepo: 'pyalarmdotcom-master', name: 'Pyalarmdotcom Inc', description: 'ML predictions with confidence intervals of maybe', role: 'caddy', icon: '🚢', rarity: 'uncommon' },
  { id: 'qmk-firmware', originalRepo: 'qmk_firmware-master', name: 'Mechanical Keeb Customizers', description: 'The tooling that tools the tools', role: 'equipment', icon: '❌', rarity: 'epic' },
  { id: 'rack', originalRepo: 'rack-master', name: 'Middleware Foundation', description: 'React patterns and regret patterns', role: 'course', icon: '🌱', rarity: 'legendary' },
  { id: 'rails-contributors', originalRepo: 'rails-contributors-master', name: 'Rails Contributors Ventures', description: 'Backend so powerful nobody uses it', role: 'employee', icon: '📊', rarity: 'uncommon' },
  { id: 'rails-html-sanitizer', originalRepo: 'rails-html-sanitizer-master', name: 'Rails Html Sanitizer Factory', description: 'Microservices for a TODO app', role: 'employee', icon: '🔓', rarity: 'uncommon' },
  { id: 'rails', originalRepo: 'rails-main', name: 'Convention Over Config Inc', description: 'Middleware that middleware middlewares', role: 'employee', icon: '📈', rarity: 'legendary' },
  { id: 'ramsey-reps-next', originalRepo: 'ramsey-reps-next-main', name: 'Ramsey Reps Next Collective', description: 'The model works on my machine', role: 'caddy', icon: '👥', rarity: 'uncommon' },
  { id: 'reactadviceapp', originalRepo: 'ReactAdviceApp-master', name: 'Reactadviceapp Ventures', description: 'Components all the way down', role: 'course', icon: '🐍', rarity: 'uncommon' },
  { id: 'react-boilerplate-cmshub-ecomm-demo', originalRepo: 'React-Boilerplate-CMSHub-Ecomm-Demo-main', name: 'React Boilerplate Cmshub Ecomm Demo Ventures', description: 'AI advice that is probably wrong', role: 'caddy', icon: '🤖', rarity: 'uncommon' },
  { id: 'reactbootcampassignment4', originalRepo: 'ReactBootCampAssignment4-main', name: 'Reactbootcampassignment4 LLC', description: 'Academic achievement unlocked', role: 'milestone', icon: '🌉', rarity: 'common' },
  { id: 'react-covid19-tracker', originalRepo: 'react-covid19-tracker-master', name: 'React Covid19 Tracker Labs', description: 'Components all the way down', role: 'course', icon: '🏢', rarity: 'legendary' },
  { id: 'reactecom', originalRepo: 'ReactEcom-main', name: 'Reactecom Collective', description: 'ML predictions with confidence intervals of maybe', role: 'caddy', icon: '🔔', rarity: 'uncommon' },
  { id: 'react-electron-boilerplate', originalRepo: 'React-Electron-BoilerPlate-master', name: 'React Electron Boilerplate Studios', description: 'Components all the way down', role: 'course', icon: '🚀', rarity: 'uncommon' },
  { id: 'react-item-mover', originalRepo: 'react-item-mover-main', name: 'React Item Mover Labs', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '📊', rarity: 'uncommon' },
  { id: 'reactivities', originalRepo: 'Reactivities-master', name: 'Reactivities Solutions', description: 'Components all the way down', role: 'course', icon: '☕', rarity: 'uncommon' },
  { id: 'react-level-1', originalRepo: 'react-level-1-master', name: 'React Level 1 Systems', description: 'UI library showcase', role: 'course', icon: '🖥️', rarity: 'common' },
  { id: 'reactnativeresume', originalRepo: 'ReactNativeResume-master', name: 'Reactnativeresume Collective', description: 'Our portfolio site has better uptime than our product', role: 'sponsor', icon: '⚛️', rarity: 'uncommon' },
  { id: 'react-native-workout-app', originalRepo: 'react-native-workout-app-main', name: 'React Native Workout App Academy', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '💻', rarity: 'uncommon' },
  { id: 'reactpersonalportfolio', originalRepo: 'ReactPersonalPortfolio-main', name: 'Reactpersonalportfolio Systems', description: 'Resume but make it interactive', role: 'sponsor', icon: '🏢', rarity: 'uncommon' },
  { id: 'react-table', originalRepo: 'react-table-master', name: 'React Table Inc', description: 'Components all the way down', role: 'course', icon: '🎓', rarity: 'uncommon' },
  { id: 'react-tictactoe', originalRepo: 'React-TicTacToe-master', name: 'React Tictactoe Collective', description: 'Components all the way down', role: 'course', icon: '🚢', rarity: 'uncommon' },
  { id: 'react-workshop-assignment1', originalRepo: 'React-Workshop-Assignment1-main', name: 'React Workshop Assignment1 Co', description: 'From zero to one star on GitHub', role: 'milestone', icon: '⚖️', rarity: 'common' },
  { id: 'react-workshop-assignment2', originalRepo: 'React-Workshop-Assignment2-main', name: 'React Workshop Assignment2 Labs', description: 'Academic achievement unlocked', role: 'milestone', icon: '🐛', rarity: 'common' },
  { id: 'react-workshop-assignment3', originalRepo: 'React-WorkShop-Assignment3-main', name: 'React Workshop Assignment3 Corp', description: 'Completed coursework that proves effort', role: 'milestone', icon: '🏠', rarity: 'common' },
  { id: 'realworld', originalRepo: 'realworld-master', name: 'Realworld Factory', description: 'Helper code that actually helps', role: 'powerup', icon: '🚢', rarity: 'uncommon' },
  { id: 'registerapidatadefinition', originalRepo: 'RegisterAPIDataDefinition-master', name: 'Registerapidatadefinition Systems', description: 'Backend so powerful nobody uses it', role: 'employee', icon: '🚀', rarity: 'uncommon' },
  { id: 'relay', originalRepo: 'relay-main', name: 'GraphQL Overcomplication Labs', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '🔥', rarity: 'legendary' },
  { id: 'rest-api-springboot', originalRepo: 'Rest-API-SpringBoot-main', name: 'Rest Api Springboot Industries', description: 'Backend so powerful nobody uses it', role: 'employee', icon: '⚡', rarity: 'uncommon' },
  { id: 'resume', originalRepo: 'Resume-master', name: 'Resume Academy', description: 'One domain to rule them all', role: 'sponsor', icon: '📱', rarity: 'uncommon' },
  { id: 'robotriffs', originalRepo: 'robotriffs-main', name: 'AI Jazz Ensemble', description: 'The model works on my machine', role: 'caddy', icon: '📣', rarity: 'rare' },
  { id: 'rock-paper-scissors', originalRepo: 'rock-paper-scissors-master', name: 'RPS Resolution Systems', description: 'DevOps chaos in a repo', role: 'hazard', icon: '💵', rarity: 'common' },
  { id: 'rom-poring-exchange', originalRepo: 'rom_poring_exchange-master', name: 'Rom Poring Exchange Corp', description: 'Academic achievement unlocked', role: 'milestone', icon: '🏆', rarity: 'rare' },
  { id: 'rottenpotatoes-rails-intro', originalRepo: 'rottenpotatoes-rails-intro-master', name: 'Rottenpotatoes Rails Intro Labs', description: 'Middleware that middleware middlewares', role: 'employee', icon: '🎵', rarity: 'common' },
  { id: 'rps-pi', originalRepo: 'RPS_Pi-main', name: 'Rps Pi Solutions', description: 'The minigame the standup needed', role: 'minigame', icon: '📦', rarity: 'uncommon' },
  { id: 'ruby-algorithms', originalRepo: 'Ruby_Algorithms-main', name: 'Ruby Algorithms LLC', description: 'Learning projects as trophies', role: 'milestone', icon: '🚀', rarity: 'uncommon' },
  { id: 'rulers', originalRepo: 'rulers-master', name: 'Rulers Systems', description: 'One domain to rule them all', role: 'sponsor', icon: '🎯', rarity: 'uncommon' },
  { id: 'rustlings', originalRepo: 'rustlings-main', name: 'Rustlings Labs', description: 'ML predictions with confidence intervals of maybe', role: 'caddy', icon: '🏆', rarity: 'uncommon' },
  { id: 'rust-playground', originalRepo: 'rust-playground-master', name: 'Rust Playground Co', description: 'Components all the way down', role: 'course', icon: '💻', rarity: 'uncommon' },
  { id: 'rwofost', originalRepo: 'Rwofost-master', name: 'Rwofost Industries', description: 'Built our product as a side project', role: 'competitor', icon: '🚢', rarity: 'uncommon' },
  { id: 'satori', originalRepo: 'satori-main', name: 'AI Clip Factory', description: 'AI advice that is probably wrong', role: 'caddy', icon: '🔄', rarity: 'uncommon' },
  { id: 'screeps-code', originalRepo: 'screeps-code-master', name: 'JS Mining Corp', description: 'The tooling that tools the tools', role: 'equipment', icon: '🎨', rarity: 'rare' },
  { id: 'searchalgorithms', originalRepo: 'searchAlgorithms-main', name: 'Searchalgorithms Studios', description: 'From zero to one star on GitHub', role: 'milestone', icon: '⚖️', rarity: 'uncommon' },
  { id: 'sentiment-analysis-first-attempt', originalRepo: 'Sentiment-Analysis-First-Attempt-main', name: 'Vibe Check Ventures', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '🛒', rarity: 'common' },
  { id: 'sfg-di', originalRepo: 'sfg-di-master', name: 'Sfg Di Collective', description: 'Engagement is our growth metric', role: 'event', icon: '🛒', rarity: 'uncommon' },
  { id: 'sfg-pet-clinic', originalRepo: 'sfg-pet-clinic-main', name: 'Sfg Pet Clinic Inc', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '🚢', rarity: 'uncommon' },
  { id: 'silasbanana', originalRepo: 'silasbanana-main', name: 'Silasbanana Solutions', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '🚢', rarity: 'uncommon' },
  { id: 'simple-java-blog', originalRepo: 'simple-java-blog-main', name: 'Simple Java Blog Solutions', description: 'AI advice that is probably wrong', role: 'caddy', icon: '🤝', rarity: 'common' },
  { id: 'site', originalRepo: 'site-main', name: 'Site Industries', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '🗺️', rarity: 'uncommon' },
  { id: 'snake-game', originalRepo: 'snake-game-master', name: 'Nokia Nostalgia Inc', description: 'Click things until something happens', role: 'minigame', icon: '🤖', rarity: 'common' },
  { id: 'social-app', originalRepo: 'social-app-main', name: 'Engagement Metrics Unlimited', description: 'Engagement is our growth metric', role: 'event', icon: '🖥️', rarity: 'uncommon' },
  { id: 'software-licence-policy', originalRepo: 'software-licence-policy-main', name: 'Software Licence Policy LLC', description: 'The model works on my machine', role: 'caddy', icon: '⚛️', rarity: 'uncommon' },
  { id: 'solidus-auth-devise', originalRepo: 'solidus_auth_devise-master', name: 'Solidus Auth Devise Collective', description: 'Microservices for a TODO app', role: 'employee', icon: '🎲', rarity: 'uncommon' },
  { id: 'solidus-bot', originalRepo: 'solidus_bot-master', name: 'Solidus Bot Factory', description: 'They pivoted to our exact idea', role: 'competitor', icon: '🎉', rarity: 'uncommon' },
  { id: 'solidus-cmd', originalRepo: 'solidus_cmd-master', name: 'Solidus Cmd Systems', description: 'SDK for the SDK wrapper', role: 'equipment', icon: '🔥', rarity: 'uncommon' },
  { id: 'solidus-graphql-api', originalRepo: 'solidus_graphql_api-master', name: 'Solidus Graphql Api Labs', description: 'Backend so powerful nobody uses it', role: 'employee', icon: '🔒', rarity: 'uncommon' },
  { id: 'solidus-i18n', originalRepo: 'solidus_i18n-master', name: 'Solidus I18n Solutions', description: 'Learning documented for posterity', role: 'trophy', icon: '📰', rarity: 'uncommon' },
  { id: 'solidus-subscriptions', originalRepo: 'solidus_subscriptions-master', name: 'Solidus Subscriptions Ventures', description: 'Boosts velocity by 2x maybe', role: 'powerup', icon: '🛒', rarity: 'uncommon' },
  { id: 'solidus', originalRepo: 'solidus-master', name: 'Spree 2 Electric Boogaloo', description: 'Config files as personality', role: 'equipment', icon: '🏠', rarity: 'uncommon' },
  { id: 'sovir', originalRepo: 'soviR-master', name: 'Sovir LLC', description: 'Config files as personality', role: 'equipment', icon: '⚖️', rarity: 'uncommon' },
  { id: 'spacetime', originalRepo: 'spacetime-master', name: 'Spacetime Systems', description: 'Our portfolio site has better uptime than our product', role: 'sponsor', icon: '🎲', rarity: 'uncommon' },
  { id: 'spec-chart', originalRepo: 'spec_chart-master', name: 'Spec Chart Co', description: 'Learning projects as trophies', role: 'milestone', icon: '📝', rarity: 'uncommon' },
  { id: 'spring5webapp', originalRepo: 'spring5webapp-master', name: 'Spring5webapp Ventures', description: 'Microservices for a TODO app', role: 'employee', icon: '👥', rarity: 'uncommon' },
  { id: 'springjokesapp', originalRepo: 'SpringJokesApp-main', name: 'Springjokesapp Ventures', description: 'API responses and existential dread', role: 'employee', icon: '🎮', rarity: 'uncommon' },
  { id: 'springrestfulservicesexample', originalRepo: 'SpringRestfulServicesExample-master', name: 'Springrestfulservicesexample Systems', description: 'Middleware that middleware middlewares', role: 'employee', icon: '🔔', rarity: 'uncommon' },
  { id: 'spue', originalRepo: 'spue-master', name: 'Spue Corp', description: 'The repo that got a star', role: 'trophy', icon: '🤖', rarity: 'uncommon' },
  { id: 'sql-queries', originalRepo: 'SQL-Queries-main', name: 'Sql Queries Corp', description: 'ML predictions with confidence intervals of maybe', role: 'caddy', icon: '🎵', rarity: 'common' },
  { id: 'stars', originalRepo: 'stars-master', name: 'Stars Collective', description: 'Where hot takes meet cold PRs', role: 'event', icon: '⌨️', rarity: 'uncommon' },
  { id: 'star-wars-api', originalRepo: 'star-wars-api-main', name: 'Star Wars Api LLC', description: 'Middleware that middleware middlewares', role: 'employee', icon: '💻', rarity: 'uncommon' },
  { id: 'storage-closet', originalRepo: 'storage-closet-main', name: 'Storage Closet Studios', description: 'The model works on my machine', role: 'caddy', icon: '🔗', rarity: 'uncommon' },
  { id: 'stream-me', originalRepo: 'stream-me-main', name: 'Stream Me Factory', description: 'Communication tool for async teams', role: 'event', icon: '🔒', rarity: 'uncommon' },
  { id: 'swot-dashboard', originalRepo: 'SWOT_Dashboard-main', name: 'Swot Dashboard Ventures', description: 'The model works on my machine', role: 'caddy', icon: '🎯', rarity: 'uncommon' },
  { id: 'tactics-game', originalRepo: 'tactics_game-main', name: 'Grid Warfare Sims', description: 'Click things until something happens', role: 'minigame', icon: '🔄', rarity: 'rare' },
  { id: 'tar1090', originalRepo: 'tar1090-master', name: 'Tar1090 Studios', description: 'YAML nightmares and config drift', role: 'hazard', icon: '❌', rarity: 'uncommon' },
  { id: 'taskly', originalRepo: 'taskly-main', name: 'Taskly Co', description: 'The model works on my machine', role: 'caddy', icon: '👥', rarity: 'uncommon' },
  { id: 'tastemap', originalRepo: 'TasteMap-main', name: 'Palate Profiling Inc', description: 'ML predictions with confidence intervals of maybe', role: 'caddy', icon: '🔒', rarity: 'uncommon' },
  { id: 'taste-map', originalRepo: 'taste-map-main', name: 'Taste Map Collective', description: 'The model works on my machine', role: 'caddy', icon: '🐳', rarity: 'uncommon' },
  { id: 'taxiproject', originalRepo: 'taxiproject-main', name: 'Taxiproject Co', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '🌉', rarity: 'rare' },
  { id: 'team-gigasowers-backend', originalRepo: 'team-gigasowers-backend-main', name: 'Team Gigasowers Backend Academy', description: 'The model works on my machine', role: 'caddy', icon: '🎨', rarity: 'uncommon' },
  { id: 'team-gigasowers-frontend', originalRepo: 'team-gigasowers-frontend-main', name: 'Team Gigasowers Frontend Corp', description: 'The model works on my machine', role: 'caddy', icon: '🏠', rarity: 'uncommon' },
  { id: 'terminal-chat', originalRepo: 'terminal-chat-master', name: 'Terminal Chat Industries', description: 'Where hot takes meet cold PRs', role: 'event', icon: '🎨', rarity: 'uncommon' },
  { id: 'terra', originalRepo: 'terra-master', name: 'Terra Studios', description: 'DevOps chaos in a repo', role: 'hazard', icon: '💵', rarity: 'uncommon' },
  { id: 'terrariaclone', originalRepo: 'TerrariaClone-master', name: '2D Sandbox Imitators', description: 'They pivoted to our exact idea', role: 'competitor', icon: '🌐', rarity: 'rare' },
  { id: 'test-assigment', originalRepo: 'test-assigment-main', name: 'Test Assigment Industries', description: 'The tool you did not know you needed', role: 'powerup', icon: '⚖️', rarity: 'common' },
  { id: 'test-git-ios-project', originalRepo: 'Test-Git-iOS-Project-master', name: 'Test Git Ios Project Industries', description: 'The tool you did not know you needed', role: 'powerup', icon: '👥', rarity: 'common' },
  { id: 'test-web-server', originalRepo: 'Test-Web-Server-master', name: 'Test Web Server Collective', description: 'Microservices for a TODO app', role: 'employee', icon: '🔧', rarity: 'common' },
  { id: 'text-befuddler', originalRepo: 'text-befuddler-master', name: 'Text Befuddler Studios', description: 'Nobody remembers why this code exists', role: 'hazard', icon: '🧪', rarity: 'uncommon' },
  { id: 'the-pragmatic-programmer', originalRepo: 'The-Pragmatic-Programmer-master', name: 'Pragmatic Press Ltd', description: 'Achievement unlocked and forgotten', role: 'trophy', icon: '🐳', rarity: 'legendary' },
  { id: 'thesis', originalRepo: 'thesis-main', name: 'Thesis Systems', description: 'The model works on my machine', role: 'caddy', icon: '📣', rarity: 'uncommon' },
  { id: 'thoughtsonbowling', originalRepo: 'thoughtsonbowling-main', name: 'Lane Philosophy Co', description: 'The minigame the standup needed', role: 'minigame', icon: '⚡', rarity: 'uncommon' },
  { id: 'tic-tac-toe', originalRepo: 'tic-tac-toe-main', name: 'Naughts Crosses Revival', description: 'Another game we built instead of working', role: 'minigame', icon: '🕳️', rarity: 'common' },
  { id: 'timeline-component', originalRepo: 'Timeline-Component-main', name: 'Timeline Component Academy', description: 'ML predictions with confidence intervals of maybe', role: 'caddy', icon: '☕', rarity: 'uncommon' },
  { id: 'tipg', originalRepo: 'tipg-main', name: 'Tipg Academy', description: 'The model works on my machine', role: 'caddy', icon: '❌', rarity: 'uncommon' },
  { id: 'tissuetracker-api-endpoint', originalRepo: 'tIssueTracker-API-Endpoint-master', name: 'Tissuetracker Api Endpoint Industries', description: 'Backend so powerful nobody uses it', role: 'employee', icon: '⚡', rarity: 'legendary' },
  { id: 'tissuetracker-webui', originalRepo: 'tIssueTracker-WebUi-master', name: 'Tissuetracker Webui Inc', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '📈', rarity: 'legendary' },
  { id: 'to-do-app', originalRepo: 'to-do-app-main', name: 'To Do App LLC', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '📦', rarity: 'common' },
  { id: 'touchtable', originalRepo: 'touchTable-main', name: 'Touchtable Co', description: 'ML predictions with confidence intervals of maybe', role: 'caddy', icon: '🌉', rarity: 'rare' },
  { id: 'tracr', originalRepo: 'tracr-main', name: 'Tracr Academy', description: 'The model works on my machine', role: 'caddy', icon: '🌱', rarity: 'uncommon' },
  { id: 'tweetmoji', originalRepo: 'tweetmoji-main', name: 'Tweetmoji Studios', description: 'Where hot takes meet cold PRs', role: 'event', icon: '🤝', rarity: 'uncommon' },
  { id: 'twiml-hosting', originalRepo: 'twiml-hosting-main', name: 'Twiml Hosting Co', description: 'AI advice that is probably wrong', role: 'caddy', icon: '👥', rarity: 'uncommon' },
  { id: 'typescript-design-patterns', originalRepo: 'TypeScript_Design_Patterns-main', name: 'Typescript Design Patterns Ventures', description: 'The model works on my machine', role: 'caddy', icon: '🌐', rarity: 'uncommon' },
  { id: 'typescriptskeleton', originalRepo: 'TypeScriptSkeleton-master', name: 'Typescriptskeleton LLC', description: 'Development setup as identity', role: 'equipment', icon: '🌉', rarity: 'uncommon' },
  { id: 'udemy-docker-mastery', originalRepo: 'udemy-docker-mastery-main', name: 'Udemy Docker Mastery Labs', description: 'Infrastructure anxiety as a feature', role: 'hazard', icon: '🛒', rarity: 'uncommon' },
  { id: 'uitableviewcontroller-challenge-solution', originalRepo: 'UITableViewController-Challenge-Solution-master', name: 'Uitableviewcontroller Challenge Solution Solutions', description: 'Another game we built instead of working', role: 'minigame', icon: '🎨', rarity: 'uncommon' },
  { id: 'umep-core', originalRepo: 'umep-core-main', name: 'Umep Core Ventures', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '🛒', rarity: 'uncommon' },
  { id: 'umusic', originalRepo: 'uMusic-master', name: 'Umusic Ventures', description: 'Academic achievement unlocked', role: 'milestone', icon: '🚀', rarity: 'rare' },
  { id: 'utils', originalRepo: 'utils-master', name: 'Utils Labs', description: 'The tool you did not know you needed', role: 'powerup', icon: '🎯', rarity: 'uncommon' },
  { id: 'verydebate', originalRepo: 'verydebate-main', name: 'Opinion Arena LLC', description: 'Communication tool for async teams', role: 'event', icon: '📝', rarity: 'uncommon' },
  { id: 'virtual-assistant', originalRepo: 'virtual-assistant-master', name: 'AI Receptionist Corp', description: 'Academic achievement unlocked', role: 'milestone', icon: '📦', rarity: 'uncommon' },
  { id: 'visual-plane-notifier', originalRepo: 'visual_plane_notifier-main', name: 'Visual Plane Notifier Factory', description: 'AI advice that is probably wrong', role: 'caddy', icon: '🤖', rarity: 'uncommon' },
  { id: 'vroom', originalRepo: 'vroom-main', name: 'Vroom LLC', description: 'ML predictions with confidence intervals of maybe', role: 'caddy', icon: '🐱', rarity: 'rare' },
  { id: 'vwline', originalRepo: 'vwline-master', name: 'Vwline Collective', description: 'Where hot takes meet cold PRs', role: 'event', icon: '🤖', rarity: 'uncommon' },
  { id: 'wavetable-morphing-synthesizer', originalRepo: 'Wavetable-Morphing-Synthesizer-master', name: 'Wavetable Morphing Synthesizer LLC', description: 'The tooling that tools the tools', role: 'equipment', icon: '⌨️', rarity: 'uncommon' },
  { id: 'weatheranim', originalRepo: 'weatheranim-master', name: 'Weatheranim Corp', description: 'The repo that got a star', role: 'trophy', icon: '🌱', rarity: 'uncommon' },
  { id: 'weather-app', originalRepo: 'weather-app-main', name: 'Weather App Inc', description: 'AI advice that is probably wrong', role: 'caddy', icon: '💰', rarity: 'common' },
  { id: 'weather-app-website', originalRepo: 'weather-app-website-master', name: 'Weather App Website Academy', description: 'Resume but make it interactive', role: 'sponsor', icon: '🔒', rarity: 'uncommon' },
  { id: 'wheatcultivars-heat-zaf', originalRepo: 'wheatcultivars_heat_zaf-master', name: 'Wheatcultivars Heat Zaf Labs', description: 'Social coding in the wild', role: 'event', icon: '🎨', rarity: 'uncommon' },
  { id: 'wine-prediction', originalRepo: 'wine-prediction-main', name: 'Sommelier AI', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '📝', rarity: 'uncommon' },
  { id: 'wod-api', originalRepo: 'Wod-api-master', name: 'Wod Api Inc', description: 'API responses and existential dread', role: 'employee', icon: '🕳️', rarity: 'uncommon' },
  { id: 'wod-client', originalRepo: 'Wod-Client-master', name: 'Wod Client Inc', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '🎵', rarity: 'uncommon' },
  { id: 'wod-react-client', originalRepo: 'Wod-React-Client-master', name: 'Wod React Client Inc', description: 'UI library showcase', role: 'course', icon: '🎵', rarity: 'uncommon' },
  { id: 'wod-spring-api', originalRepo: 'Wod-Spring-Api-master', name: 'Wod Spring Api Labs', description: 'API responses and existential dread', role: 'employee', icon: '👥', rarity: 'uncommon' },
  { id: 'working-woodfern', originalRepo: 'working-woodfern-main', name: 'Working Woodfern Solutions', description: 'AI advice that is probably wrong', role: 'caddy', icon: '📣', rarity: 'uncommon' },
  { id: 'would-you-rather', originalRepo: 'would-you-rather-main', name: 'Impossible Choice Games', description: 'The model works on my machine', role: 'caddy', icon: '🎮', rarity: 'uncommon' },
  { id: 'www-ruby-lang-org', originalRepo: 'www.ruby-lang.org-master', name: 'Ruby Temple Archives', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '🏆', rarity: 'uncommon' },
  { id: 'yahtzee', originalRepo: 'Yahtzee-main', name: 'Dice Deciders Inc', description: 'Another game we built instead of working', role: 'minigame', icon: '🤖', rarity: 'uncommon' },
  { id: 'yaleskateboarding', originalRepo: 'yaleskateboarding-main', name: 'Yaleskateboarding Academy', description: 'Artificial intelligence natural mistakes', role: 'caddy', icon: '🔔', rarity: 'uncommon' },
  { id: 'yield-monitor', originalRepo: 'yield-monitor-main', name: 'Yield Monitor LLC', description: 'The model works on my machine', role: 'caddy', icon: '⚖️', rarity: 'uncommon' },
  { id: 'zmk-fourier', originalRepo: 'zmk-fourier-master', name: 'Keeb Config Collective', description: 'Config files as personality', role: 'equipment', icon: '🤖', rarity: 'uncommon' },
  { id: 'zmk-roadrunner', originalRepo: 'zmk-roadrunner-main', name: 'Split Keyboard Syndicate', description: 'ML predictions with confidence intervals of maybe', role: 'caddy', icon: '📰', rarity: 'uncommon' },
];

export const getByRole = (role: GameRole) => GAME_ENTITIES.filter(e => e.role === role);
export const getById = (id: string) => GAME_ENTITIES.find(e => e.id === id);
export const getRandomByRole = (role: GameRole) => { const pool = getByRole(role); return pool[Math.floor(Math.random() * pool.length)]; };
export const getAllMinigames = () => getByRole('minigame');
export const getAllSponsors = () => getByRole('sponsor');
export const getAllEmployees = () => getByRole('employee');
export const getAllCompetitors = () => getByRole('competitor');
export const getByOriginalRepo = (repo: string) => GAME_ENTITIES.find(e => e.originalRepo === repo);
